.TH "AppDelegate" 3 "Tue Feb 14 2012" "AVTestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AppDelegate \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <AppDelegate\&.h>\fP
.SS "Properties"

.in +1c
.ti -1c
.RI "UIWindow * \fBwindow\fP"
.br
.in -1c
.SH "Property Documentation"
.PP 
.SS "- (UIWindow*) \fBwindow\fP\fC [read, write, assign]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for AVTestApp from the source code\&.
