.TH "/Users/Chris/Desktop/workspace/AVTestApp/AVTestApp/main.m" 3 "Tue Feb 14 2012" "AVTestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Chris/Desktop/workspace/AVTestApp/AVTestApp/main.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import <UIKit/UIKit\&.h>\fP
.br
\fC#import 'AppDelegate\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int \fBmain\fP (intargc, char *argv[])"
.SH "Author"
.PP 
Generated automatically by Doxygen for AVTestApp from the source code\&.
