.TH "/Users/Chris/Desktop/workspace/AVTestApp/AVTestApp/PickPhotoViewController.m" 3 "Tue Feb 14 2012" "AVTestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Chris/Desktop/workspace/AVTestApp/AVTestApp/PickPhotoViewController.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'PickPhotoViewController\&.h'\fP
.br
\fC#import <MobileCoreServices/UTCoreTypes\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AVTestApp from the source code\&.
