.TH "PickPhotoViewController" 3 "Tue Feb 14 2012" "AVTestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PickPhotoViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <PickPhotoViewController\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(IBAction) - \fBuseCamera:\fP"
.br
.ti -1c
.RI "(IBAction) - \fBuseCameraRoll:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IBOutlet UIImageView * \fBimageView\fP"
.br
.ti -1c
.RI "BOOL \fBnewMedia\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (IBAction) \fBuseCamera:\fP (id)sender"
.SS "- (IBAction) \fBuseCameraRoll:\fP (id)sender"
.SH "Property Documentation"
.PP 
.SS "- (IBOutlet UIImageView*) \fBimageView\fP\fC [read, write, retain]\fP"
.SS "- (BOOL) \fBnewMedia\fP\fC [read, write, assign]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for AVTestApp from the source code\&.
