.TH "/Users/Chris/Desktop/workspace/AVTestApp/AVTestApp/PickPhotoViewController.h" 3 "Tue Feb 14 2012" "AVTestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Chris/Desktop/workspace/AVTestApp/AVTestApp/PickPhotoViewController.h \- 
.SH SYNOPSIS
.br
.PP
\fC#import <UIKit/UIKit\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPickPhotoViewController\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AVTestApp from the source code\&.
