.TH "RecordAudioViewController" 3 "Tue Feb 14 2012" "AVTestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RecordAudioViewController \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#import <RecordAudioViewController\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(IBAction) - \fBrecordAudio:\fP"
.br
.ti -1c
.RI "(IBAction) - \fBplayAudio:\fP"
.br
.ti -1c
.RI "(IBAction) - \fBstop:\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "AVAudioRecorder * \fBaudioRecorder\fP"
.br
.ti -1c
.RI "AVAudioPlayer * \fBaudioPlayer\fP"
.br
.ti -1c
.RI "IBOutlet UIBarButtonItem * \fBplayButton\fP"
.br
.ti -1c
.RI "IBOutlet UIBarButtonItem * \fBrecordButton\fP"
.br
.ti -1c
.RI "IBOutlet UIBarButtonItem * \fBstopButton\fP"
.br
.ti -1c
.RI "IBOutlet UILabel * \fBstateLabel\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "- (IBAction) \fBplayAudio:\fP (id)sender"
.SS "- (IBAction) \fBrecordAudio:\fP (id)sender"
.SS "- (IBAction) \fBstop:\fP (id)sender"
.SH "Property Documentation"
.PP 
.SS "- (AVAudioPlayer*) \fBaudioPlayer\fP\fC [read, write, retain]\fP"
.SS "- (AVAudioRecorder*) \fBaudioRecorder\fP\fC [read, write, retain]\fP"
.SS "- (IBOutlet UIBarButtonItem*) \fBplayButton\fP\fC [read, write, retain]\fP"
.SS "- (IBOutlet UIBarButtonItem*) \fBrecordButton\fP\fC [read, write, retain]\fP"
.SS "- (IBOutlet UILabel*) \fBstateLabel\fP\fC [read, write, retain]\fP"
.SS "- (IBOutlet UIBarButtonItem*) \fBstopButton\fP\fC [read, write, retain]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for AVTestApp from the source code\&.
