.TH "/Users/Chris/Desktop/workspace/AVTestApp/AVTestApp/RecordAudioViewController.m" 3 "Tue Feb 14 2012" "AVTestApp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/Chris/Desktop/workspace/AVTestApp/AVTestApp/RecordAudioViewController.m \- 
.SH SYNOPSIS
.br
.PP
\fC#import 'RecordAudioViewController\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AVTestApp from the source code\&.
